# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
permissions:
  contents: write
  
name: Get Race Schedule
on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch: # Needed to allow for manual workflow runs (mostly for testing)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        
    # Below is what will fetch the data, note that we don't use any node packages to so no npm install needed
    - name: Fetch Race Data
      run: |
        node src/api/get-schedule.js 
        node src/api/get-year-schedule.js
    - name: Commit and Push Changes
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./public/data/schedule.json
          git add ./public/data/year_schedule.json
          git commit -m "chore: update generated files" || echo "No changes to commit"
          git push
